Downgrade back to jnr-posix 3.0.42 - Seeing some possible issues with 3.0.42 (or conflicts with Netty 4.1?)
java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: could not locate stub library in jar file.  Tried [jni/x86_64-Linux/libjffi-1.2.so, /jni/x86_64-Linux/libjffi-1.2.so]