Revert to jnr-posix 3.0.1 since I'm getting an error on 3.0.9
Failed to load native POSIX impl; falling back on Java impl. Stacktrace follows.
java.lang.UnsatisfiedLinkError: libcrypt.so: cannot open shared object file: No such file or directory